---
title: "NYC Restaurant Inspection Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
```

```{r reorganize data for chart A, include = FALSE}
data("rest_inspec")

cuisine_desc = rest_inspec %>% 
  group_by(cuisine_description) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  mutate(is_other = ifelse(count < 10000, "yes", "no"))

cuisine_other = cuisine_desc %>%
filter(is_other == "yes") %>%
mutate(total_count = sum(count))
```


Column {data-width=650}
-----------------------------------------------------------------------



### Chart A

```{r, include = FALSE}
most_cuisine = cuisine_desc %>%
  filter(is_other == "no") %>%
  add_row(cuisine_description = "other restaurant",
          count = sum(cuisine_other$count)) %>%
    mutate(cuisine_description = fct_reorder(cuisine_description, count),
           cuisine_description = fct_recode(
      cuisine_description, 
      "Latin" = "Latin (Cuban, Dominican, Puerto Rican, South & Central American)",
      "Juice" = "Juice, Smoothies, Fruit Salads" ,
      "Mixed Buffet" = "Sandwiches/Salads/Mixed Buffet" ,
      "Beverages" = "Bottled beverages, including water, sodas, juices, etc.")) %>%
  select(cuisine_description, count)
```

```{r}
  plot_ly(most_cuisine, x = ~cuisine_description, y = ~count, type = 'bar') %>%
  layout(title = 'Violation times regarding cuisines categories',
         xaxis = list(title = "Cusion Description")) 
```


```{r reorganize data for chart B, include = FALSE}
boro_inspec = rest_inspec %>% 
  drop_na(score) %>% 
  select(boro, score) %>%
  filter(boro %in% c("MANHATTAN", "BRONX", "BROOKLYN", "QUEENS", "STATEN ISLAND")) %>%
  mutate(boro = fct_reorder(boro, score)) 
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
boro_inspec %>%
  plot_ly(y = ~score, color = ~boro, type = "box") %>%
  layout(title = "Inspection score by boroughs",
         xaxis = list(title = "Borough name")) 
```


### Chart C
```{r}
rest_inspec %>%
  filter(grade %in% c("A","B","C"), boro == "MANHATTAN") %>%
  mutate(cuisine_description = fct_reorder(cuisine_description,score)) %>%
  mutate(
    cuisine_description = as.factor(cuisine_description),
    cuisine_description = fct_recode(
      cuisine_description, 
      "Latin" = "Latin (Cuban, Dominican, Puerto Rican, South & Central American)",
      "Juice" = "Juice, Smoothies, Fruit Salads" ,
      "Mixed Buffet" = "Sandwiches/Salads/Mixed Buffet" ,
      "Beverages" = "Bottled beverages, including water, sodas, juices, etc.")) %>%
    mutate(
    text_label = str_c("grade: ", grade)
  ) %>%
  plot_ly(
    x = ~cuisine_description, y = ~score, 
    color = ~grade , alpha = 0.5,
    type = "scatter", mode = "markers", colors = "viridis"
  ) %>%
  layout(title = 'Scores spreading according to cuisine types in Manhattan',
         xaxis = list(title = "Cuisine descriptions"),
         yaxis = list(title = "Score"))
```


