---
title: "Resume"
output: 
  html_document:
    toc: true
    toc_float: true
---

### Education
* MS in Biostatistics, Columbia University, 08/2022 -- present
* BS in Data Science with minor in mathematics, University of Michigan, 08/2020 -- 04/2022
* BS in Statistics, University of Washington, 08/2018 -- 06/2020

### Skills
* Programming Language: Java, C/C++, R Studio(markdown, ggplot2), SQL, SAS, Python, MATLAB
* Developer Tools: VS Code, Xcode, Git, Jupyter Notebook,Microsoft Excel, Microsoft Office
* Statistics and ML Skills: Regression, Decision Trees, Random Forest, K-means Clustering, Bayesian Statistics, Data 					Visualization, Forecasting and Planning

### Work Experience
**Statistics Intern, Biostatistics Department at I-MAB Biopharma**	
  06/2022 -- 08/2022, Gaithersburg, MD

  + Reorganized and cleaned original clinical data using Microsoft Excel according to the format in the trail protocol
Visualized data using both R and SAS and highlighted important information on the graphs, revised the graphs according to the progress of the trails

  + Updated and improved the graphs’ quality using ggplot2, made interpretations based on the results, and communicated results with coworkers during weekly meetings

**Statistics Intern, Statistics Analysis Department at MacroStat (China) Clinical Research Co., Ltd., Tigermed**	

  05/2021 -- 08/2021, Wuhan, CN

  + Learned the complete Standard Operating Procedure for a Contract Research Organization and applied them to example scenarios and real situations
  
  + Utilized SAS to reorganize over 50 simulated databases and 10 databases provided by clients, and revised the existed functions, which increased efficiency by around 20%
  
  + Assisted manager in refining and checking the formats of over 200 tables required by partner companies

**Data Analyst Intern, Strategic Investment Department at The Arena Capital**	

  08/2020 -- 09/2020, Shanghai, CN

*Cases: Trading Card Market in China; Domestic Male Personal Care; Government’s Control Over Dietary Supplement; Scale Model Kit and Blind Toy Box Market*
  
  + Collaborated to collect sale information from over 500 potential companies from annual reports, set up face-to-face interviews, anonymously surveyed popular E-commerce platform feedback
  
  + Communicated with 23 targeting companies, updated meeting notes, and evaluated products as a customer
  
  + Developed concise proposals using Excel and PowerPoint and delivered presentations in front of teams

### Research Experience

**Vaccine Adverse Event Reporting System Analysis**


*Researcher, Supervised by Dr.Oliver He, Ann Arbor, MI, 05/2022 -- 08/2022*

  + Assembled similar cases in other fields and filter possible methods for future adaptation. Modified methods like EBGM and openEBGM, tested with simulated dataset, and implement with over 10,000 cases provided on the VAER website
  
  + Reflected on the limitations of methods and atypical warnings. Provided alternative methods and compared the results

**Factors That Influence Covid-19 Vaccination Rate**

*Researcher, Michigan Data Science Team	in Ann Arbor, MI, 08/2021 -- 04/2022*

  + Focused on studying the factors including government policy, economy, education that influence vaccination rate; Explored Kaggle to gather and select over 50,000 pieces of data
  
  + Reviewed and manipulated python on Jupyter Notebook to clean and filter valid Covid-19 vaccination-related data, and decreased computational rate by 65.5%
  
  + Conducted regression model analysis and performed data visualization the provide visual aid

**Modeling Immunotherapy of The Tumor**


*Researcher, Supervised by Dr. Jackson Trachette in Ann Arbor, MI, 08/2021 -- 12/2021*

  + Used background information to generate at least 3 possible models of tumor-immune interaction, and translated them into several equations that could reflect relationships and simplified them with methods like nondimensionalization
  
  + Optimized models by adding equations that incorporated interventions of other factors and possible treatments
  
  + Performed steady states analysis, generated phase portraits and bifurcation diagrams for our models using MATLAB, and compared the results under different conditions and provided insights regarding possible immunotherapy solutions
  
**Lorenz and Concentration Curves, Nutrition Inequality, and Implications for Adult Health**
  
*Research Assistant, Supervised by Dr. Kerby Shedden in Ann Arbor, MI,  01/2021 -- 04/2021*

  + Consulted and utilized statistics concepts (focus on Lorenz curve, lowess algorithm, concentration curve, etc.) on simulated data in R studio
  
  + Stratified the database with 8 categories and operated data visualization by sex and age using R studio, and instilled potential interactions with background information



